### ISSUE TITLE
PythonOperator: airflow.exceptions.AirflowException: `python_callable` param must be callable

### ISSUE THREAD

**Issue by afrazsalim** [pipeline-tools/gusty#73]
I have following  yaml file  and when I try to pass to gusty to create a task then i get issue.

**Yaml content**
```
operator: airflow.operators.python_operator.PythonOperator
task_id: isu_0bilblk_itm_text_full
python_callable: run_sap_ds_func
provide_context: 'True'
op_kwargs:
  jobname: isu_0bilblk_itm_text_full
  systemconfiguration: Current
  environment: NOPROD
```

The contents of create dag are as shown below:

```
dag = create_dag(
    hello_dag_dir,
    dag_constructors={
        'run_sap_ds_func': run_sap_ds_func
    },
    user_defined_macros={
        'run_sap_ds_func': run_sap_ds_func
      },
    latest_only=False,
    schedule_interval="0 1 * * *",
    default_args={
        "owner": "airflow",
        "depends_on_past": False,
        "start_date": days_ago(1),
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 1,
        "retry_delay": timedelta(minutes=5),
        'max_active_runs': 1
    },
)
```

Function is defined like this:
```
def run_sap_ds_func(**kwargs):
    print(kwargs)
    return "s"
```

**Error:**
Broken DAG: [/home/jr6616/airflow/dags/GEMS_B2B_BE.py]
Traceback (most recent call last):
  File "/home/jr6616/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 501, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/jr6616/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 225, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable

Is there any solution for this?
