### ISSUE TITLE
could not determine a constructor for the tag '!time'   in "<unicode string>", line 3, column 14:     target_time: !time                   ^

### ISSUE THREAD

**Issue by afrazsalim** [pipeline-tools/gusty#76]
I am trying to use TimeSensor using yaml file. However, it is difficult to pass target_time parameter. The examples provided here use timedelta that takes only one argument. However, It is not clear how to deal with functions that take multiple arguments.

Here is the complete example to reproduce the issue:

I have a yaml file name, wait_until_2pm.yml
```
operator: airflow.sensors.time_sensor.TimeSensor
task_id: wait_until_2pm
target_time: !time 
  hour: 20
  minute: 00
  second: 00
poke_interval: 60   
timeout: 3600          
mode: poke             
```

I have another file, called run_after_wait.yml.

```
operator: airflow.operators.bash.BashOperator
task_id: run_after_wait
bash_command: echo "It's 2 PM UTC. Proceeding with the task."
dependencies:
  - wait_until_2pm

```

METADATA.yml file.

```
description: "An example of a DAG created using METADATA.yml"
schedule_interval: "1 0 * * *"
default_args:
    owner: airflow
    depends_on_past: False
    start_date: !days_ago 1
    email: airflow@example.com
    email_on_failure: False
    email_on_retry: False
    retries: 1
    retry_delay: !timedelta 'minutes: 5'
```

And finally, a python file to create dag. 
  
```
import os
from datetime import datetime, timedelta, time
from airflow.utils.dates import days_ago
from gusty import create_dag
import requests
from airflow.hooks.base_hook import BaseHook



hello_dag_dir = os.path.join(
  os.environ["AIRFLOW_HOME"],
  "dags",
  "sensor_example")

# Create the DAG from the specified directory
dag = create_dag(
    hello_dag_dir,
    latest_only=False,
    schedule_interval='30 1 * * *',
    catchup=False,
    concurrency=5,
    max_active_tasks_per_dag=5,
    non_pooled_task_slot_count=5,
    max_active_runs=1,
    default_args={
        "owner": "Test",
        "depends_on_past": False,
        "start_date": days_ago(100),
        "email_on_failure": False
    }
)
```

The code does not work as the it throws following error:

```
Broken DAG: [/usr/local/airflow/dags/sensor_dag.py]
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!time'
  in "<unicode string>", line 3, column 14:
    target_time: !time 
```

Does gusty allow to use function that takes multiple arguments?

**Comment by chriscardillo** [comment]
Hi @afrazsalim. The good news is this is an easy fix. There are two issues:

1. `time` is not "registered" as a constructor (e.g. `!time`).
2. `time` is class, not a function. Constructors have to be functions.

Let's tackle each issue.

### `time` is class, not a function

In the file where you are creating the DAG, add a function that returns the desired class:

```python3
def make_time(hour=0, minute=0, second=0):
    return time(hour, minute, second)
```

### `time` is not "registered" as a constructor

To register the above function, `make_time`, as a constructor, add it to the `user_defined_macros ` argument in `create_dag` .

```python3
create_dag(
  ...,
  user_defined_macros=[make_time]
)
```

Both lists and dicts are usable when specifying `user_defined_macros` in `create_dag`.

---

Now, in your `wait_until_2pm` YAML, you will be able to successfully invoke `make_time` as a constructor:

```yaml
operator: airflow.sensors.time_sensor.TimeSensor
target_time: !make_time 
  hour: 20
  minute: 00
  second: 00
poke_interval: 60   
timeout: 3600          
mode: poke      
```

Also please note `task_id` is not a required argument in task definitions, as the file name becomes the task name.

For more information on constructors in gusty, see docs [here](https://pipeline-tools.github.io/gusty-docs/using-constructors.html). Let me know if this works out for you.
